/*
* generated by Xtext
*/
package org.xtext.example.qdsl.ui.contentassist;

import org.xtext.example.qdsl.ui.contentassist.AbstractQDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QDslProposalProvider extends AbstractQDslProposalProvider {

}
