/*
 * generated by Xtext
 */
package org.xtext.example.qdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QDslRuntimeModule extends org.xtext.example.qdsl.AbstractQDslRuntimeModule {

}
