/*
 * generated by Xtext
 */
package org.xtext.example.qdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.qdsl.ui.internal.QDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QDslActivator.getInstance().getInjector(QDslActivator.ORG_XTEXT_EXAMPLE_QDSL_QDSL);
	}
	
}
